/*
import { useState } from "react";
import { collection, addDoc } from "firebase/firestore"; 

///Building_id,,HOA_chairman,HOA_monthly_payment,building_num ,entrance ,manager

export function NewBuilding() {
        
    const [HOA_aprt_num, setHOA_aprt_num] = useState("1")
    const [HOA_chairman, setHOA_chairman] = useState("re")
    const [HOA_monthly_payment, setHOA_monthly_payment] = useState("tr")
    const [building_num, setBuilding_num] = useState("yt")
    const [entrance, setEntrance] = useState("uy")
    const [manager, setManager] = useState("ki")

    async function addNewBuilding() {
        const res= await db.collection('building').add({
            HOA_appr_num:HOA_aprt_num ,
                HOA_chairman: HOA_chairman,
                HOA_monthly_payment:HOA_monthly_payment,
                building_num:building_num,
                entrance:entrance,
                manager:manager
        })
        
      /*  
        addDoc(
            collection(db, "building"),
            {
                HOA_appr_num:HOA_aprt_num ,
                HOA_chairman: HOA_chairman,
                HOA_monthly_payment:HOA_monthly_payment,
                building_num:building_num,
                entrance:entrance,
                manager:manager
            })
    
        }

    


    
    ///for each field add an input tag except the id that will be generated by "firebase"
    
    return <div>
        <input type="text" value={HOA_aprt_num} onChange={(e) => setHOA_aprt_num(e.target.value)} />
        <input type="text" value={HOA_chairman} onChange={(e) => setHOA_chairman(e.target.value)} />
        <input type="text" value={HOA_monthly_payment} onChange={(e) => setHOA_monthly_payment(e.target.value)} />
        <input type="text" value={building_num} onChange={(e) => setBuilding_num(e.target.value)} />
        <input type="text" value={entrance} onChange={(e) => setEntrance(e.target.value)} />
        <input type="text" value={manager} onChange={(e) => setManager(e.target.value)} />
        
        <button onClick={addNewBuilding}> Add new building </button>
    </div>

}
*/