import { useState } from "react";


///Building_id,,HOA_chairman,HOA_monthly_payment,building_num ,entrance ,manager

export function newBuilding() {
        
    const [name, setName] = useState("")

    async function addNewBuilding() {
        await setDoc(
            doc(citiesRef, name),
            {
                Building_id: Building_id,
                HOA_appr_num:HOA_appr_num ,
                HOA_chairman: HOA_monthly_payment
            })
    }


    /*
    for each field add an input tag exept the id that will be generated by "firebase"
    */
    return <div>
        <input type="text" value={building_num} onChange={(e) => setName(e.target.value)} />
        <input type="text" value={name} onChange={(e) => setName(e.target.value)} />


        <button onClick={addNewCity}> Add new city </button>
    </div>

}